# √ This file will define a Kubernetes Job to execute the helm command on a pod within the EKS cluster.
apiVersion: batch/v1
kind: Job
metadata:
  name: deploy-echo-server
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: helm
        image: alpine/helm:latest
        command: ["/bin/sh", "-c"]
        args:
          - |
            helm upgrade --install echo-server ./echo_server_chart
      # imagePullSecrets:
      # - name: my-registry-credentials  # Replace with the name of your image pull secret if needed
